openapi: 3.0.0
info:
  title: caribe api
  version: '1.0'
  contact:
    email: rubenrequena@gmail.com
    name: Ruben Requena
  description: API para las taquillas de escritorio del sistema CaribeApuesta
servers:
  - url: 'http://51.83.141.121:3000'
paths:
  /auth/:
    post:
      summary: Autenticacion
      operationId: post-auth
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  activo:
                    type: boolean
                  jerarquia:
                    type: array
                    items:
                      type: string
                  moneda:
                    type: object
                    properties:
                      _id:
                        type: string
                      nombre:
                        type: string
                      siglas:
                        type: string
                  nombre:
                    type: string
                  usuario:
                    type: string
                  rol:
                    type: string
                  correo:
                    type: string
                  telefono:
                    type: string
                  permisos:
                    type: array
                    items:
                      type: integer
                  codigo:
                    type: string
                  token:
                    type: string
                  grupoPago:
                    type: string
              examples:
                Ejemplo:
                  value:
                    _id: 5fac30a3d417f82b2ccbba87
                    activo: true
                    jerarquia:
                      - 5fac0cb3f4131413ec042696
                      - 5fac30a3d417f82b2ccbba76
                    moneda:
                      _id: 5f3f9f72e8430007447ced9b
                      nombre: Bolivar
                      siglas: ves
                      principal: true
                      __v: 0
                    nombre: ONLINE 1
                    usuario: online1
                    clave: 81dc9bdb52d04dc20036dbd8313ed055
                    rol: online
                    correo: online1@gmail.com
                    telefono: '04149970167'
                    permisos:
                      - 1
                      - 10
                      - 11
                      - 20
                      - 21
                      - 22
                      - 23
                      - 30
                      - 31
                      - 40
                      - 41
                      - 50
                      - 51
                      - 52
                      - 60
                      - 61
                      - 70
                      - 71
                      - 72
                    codigo: 0-63-29
                    grupoPago: 5fac30a3d417f82b2ccbba80
                    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmFjMzBhM2Q0MTdmODJiMmNjYmJhODciLCJub21icmUiOiJPTkxJTkUgMSIsInJvbCI6Im9ubGluZSIsImplcmFycXVpYSI6WyI1ZmFjMGNiM2Y0MTMxNDEzZWMwNDI2OTYiLCI1ZmFjMzBhM2Q0MTdmODJiMmNjYmJhNzYiXSwibW9uZWRhIjpbeyJfaWQiOiI1ZjNmOWY3MmU4NDMwMDA3NDQ3Y2VkOWIiLCJub21icmUiOiJCb2xpdmFyIiwic2lnbGFzIjoidmVzIiwicHJpbmNpcGFsIjp0cnVlLCJfX3YiOjB9XSwicGVybWlzb3MiOiI1ZmFjMGNiM2Y0MTMxNDEzZWMwNDI2OTciLCJpYXQiOjE2MDUxMjAyMTksImV4cCI6MTYwNTIwNjYxOX0.Q0SWiLnNQJUnXcttu5VAIIoK0kBJiDzUk4ecNE0SJZw
      description: punto de acceso para iniciar sesion
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario:
                  type: string
                clave:
                  type: string
            examples:
              ejemplo:
                value:
                  usuario: pos1
                  clave: '1234'
        description: Solicitar inicio de sesion
      tags:
        - Sesion
    parameters: []
  /sorteo/disponibles:
    get:
      summary: sorteos disponibles
      tags:
        - sorteos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      minLength: 1
                    operadora:
                      type: string
                      minLength: 1
                    sorteos:
                      type: array
                      uniqueItems: true
                      minItems: 1
                      items:
                        type: object
                        properties:
                          _id:
                            type: string
                            minLength: 1
                          abierta:
                            type: boolean
                          descripcion:
                            type: string
                            minLength: 1
                          cierra:
                            type: string
                            minLength: 1
                        required:
                          - _id
                          - abierta
                          - descripcion
                          - cierra
                  required:
                    - _id
                    - operadora
                    - sorteos
              examples:
                ejemplo 1:
                  value:
                    - _id: 5fac6a25752eb23494950e9e
                      sorteos:
                        - _id: 5fac755a49aef72824ceb02d
                          abierta: true
                          descripcion: 'GRANJITA 05:00 AM'
                          cierra: '2020-11-12T04:00:00.000Z'
                          __v: 0
                        - _id: 5fac755a49aef72824ceb02e
                          abierta: true
                          descripcion: 'GRANJITA 12:00 PM'
                          cierra: '2020-11-12T11:00:00.000Z'
                          __v: 0
                        - _id: 5fac755a49aef72824ceb02f
                          abierta: true
                          descripcion: 'GRANJITA 11:59 PM'
                          cierra: '2020-11-12T22:59:00.000Z'
                          __v: 0
                      operadora: GRANJITA
          headers: {}
      operationId: get-sorteos-dispnibles
      description: Obtener listado de sorteos disponibles
    parameters: []
  /sorteo/conganador:
    get:
      summary: sorteos premiados
      tags:
        - sorteos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      minLength: 1
                    descripcion:
                      type: string
                      minLength: 1
                    ganador:
                      type: string
                      minLength: 1
                  required:
                    - _id
                    - descripcion
                    - ganador
      operationId: get-sorteo-conganador
      description: Obtener el listado de sorteos premiados del dia
      parameters:
        - schema:
            type: string
          in: query
          name: operadora
          description: id de la operadora
          required: true
  /sorteo/buscar/fecha:
    get:
      summary: buscar sorteos
      tags:
        - sorteos
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sorteo'
      operationId: get-sorteo-buscar-fecha
      description: Buscar el listado de sorteos del dia solicitado
      parameters:
        - schema:
            type: string
            pattern: '\d{4}-\d{2}-\d{2}'
            minLength: 10
            maxLength: 10
            format: date
            example: '2020-11-11'
          in: query
          name: fecha
          required: true
          description: fecha en formato ISODate
        - schema:
            type: string
          in: query
          name: operadora
          description: id operadora
          required: true
  /ticket/venta:
    post:
      summary: vender
      operationId: post-ticket-venta
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  ticket:
                    type: object
                    required:
                      - codigo
                      - serial
                      - creado
                      - monto
                      - anulado
                      - _id
                    properties:
                      codigo:
                        type: integer
                      serial:
                        type: string
                        minLength: 1
                      creado:
                        type: string
                        minLength: 1
                      monto:
                        type: number
                      anulado:
                        type: boolean
                      _id:
                        type: string
                        minLength: 1
                required:
                  - ticket
      description: Vender ticket
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  numero:
                    type: string
                    example: '10'
                    minLength: 1
                    maxLength: 3
                  sorteo:
                    type: string
                    description: id del sorteo
                  monto:
                    type: number
                    minimum: 1
                    example: 10000
                required:
                  - numero
                  - sorteo
                  - monto
        description: ''
      tags:
        - ticket
  /ticket/buscar/serial:
    get:
      summary: buscar ticket
      tags:
        - ticket
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  _id:
                    type: string
                    minLength: 1
                  codigo:
                    type: number
                  serial:
                    type: string
                    minLength: 1
                  creado:
                    type: string
                    minLength: 1
                  monto:
                    type: number
                  anulado:
                    type: boolean
                  moneda:
                    type: string
                    minLength: 1
                  ventas:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          minLength: 1
                        premio:
                          type: boolean
                        pagado:
                          type: boolean
                        numero:
                          type: string
                          minLength: 1
                        sorteo:
                          type: string
                          minLength: 1
                        monto:
                          type: number
                      required:
                        - _id
                        - premio
                        - pagado
                        - numero
                        - sorteo
                        - monto
                  sorteos:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          minLength: 1
                        descripcion:
                          type: string
                          minLength: 1
                        operadora:
                          type: string
                          minLength: 1
                      required:
                        - _id
                        - descripcion
                        - operadora
                  operadoras:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        _id:
                          type: string
                          minLength: 1
                        nombre:
                          type: string
                          minLength: 1
                      required:
                        - _id
                        - nombre
                required:
                  - _id
                  - codigo
                  - serial
                  - creado
                  - monto
                  - anulado
                  - moneda
                  - ventas
                  - sorteos
                  - operadoras
      operationId: get-ticket-buscar-serial
      description: buscar ticket por serial
      parameters:
        - schema:
            type: string
          in: query
          name: serial
          required: true
          description: Serial del ticket
  /ticket/buscar/ultimos:
    get:
      summary: buscar ultimos tickets
      tags:
        - ticket
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  properties:
                    anulado:
                      type: boolean
                    codigo:
                      type: number
                    creado:
                      type: string
                      minLength: 1
                    moneda:
                      type: string
                      minLength: 1
                    monto:
                      type: number
                    serial:
                      type: string
                      minLength: 1
                    _id:
                      type: string
                      minLength: 1
                  required:
                    - anulado
                    - codigo
                    - creado
                    - moneda
                    - monto
                    - serial
                    - _id
              examples:
                ejemplo:
                  value:
                    - anulado: true
                      codigo: 0
                      creado: string
                      moneda: string
                      monto: 0
                      serial: string
                      _id: string
      operationId: get-ticket-buscar-ultimos
      description: Buscar ultimos tickets vendidos
      parameters:
        - schema:
            type: number
          in: query
          name: pagina
  /ticket/anular:
    post:
      summary: anular ticket
      operationId: post-ticket-anular
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  mensaje:
                    type: string
      description: Anular ticket
      tags:
        - ticket
      parameters:
        - schema:
            type: string
            example: A12356
          in: query
          name: serial
          description: serial del ticket
          required: true
        - schema:
            type: integer
            example: 1234
            format: int32
            minimum: 1000
            maximum: 9999
          in: query
          name: codigo
          description: codigo de seguridad del ticket
          required: true
  /api/pos/reporte/general:
    get:
      description: Reporte de Usuario
      summary: Reporte Usuario
      tags:
        - Reportes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: ''
                minItems: 1
                uniqueItems: true
                items:
                  type: object
                  required:
                    - _id
                    - venta
                    - premio
                    - tickets
                    - subtotal
                    - comision
                    - participacion
                    - total
                    - operadora
                  properties:
                    _id:
                      type: string
                      minLength: 1
                    venta:
                      type: number
                    premio:
                      type: number
                    tickets:
                      type: number
                    subtotal:
                      type: number
                    comision:
                      type: number
                    participacion:
                      type: number
                    total:
                      type: number
                    operadora:
                      type: string
                      minLength: 1
      operationId: get-api-pos-reporte-general-usuario
      parameters:
        - schema:
            type: string
          in: query
          name: usuario
          required: true
        - schema:
            type: string
          in: query
          name: desde
          required: true
        - schema:
            type: string
          in: query
          name: hasta
          required: true
    parameters: []
  /api/pos/reporte/tickets:
    get:
      summary: Reporte de Ventas por ticket
      tags:
        - Reportes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    serial:
                      type: string
                    creado:
                      type: string
                    monto:
                      type: number
                    anulado:
                      type: boolean
              examples:
                Ejemplo:
                  value:
                    - _id: 5fac7c504bee0e385880be81
                      serial: A11121
                      creado: '2020-11-11 14:00:00'
                      monto: 10000
                      anulado: true
      operationId: get-api-pos-reporte-ventas
      description: Reporte de venta
      parameters:
        - schema:
            type: string
          in: query
          name: fecha
          required: true
        - schema:
            type: string
            enum:
              - venta
              - premiado
              - pagado
              - pendiente
              - anulado
            default: venta
          in: query
          name: estado
          required: true
        - schema:
            type: string
            default: ves
          in: query
          name: moneda
          required: true
        - schema:
            type: string
            example: Bearer ahstfgsnbqys...
          in: header
          name: Authenticacion
    parameters: []
  /ticket/pagar:
    get:
      description: Pagar ticket
      summary: Pagar ticket
      tags:
        - ticket
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  mensaje:
                    type: string
      operationId: get-ticket-pagar
      parameters:
        - schema:
            type: string
          in: query
          name: serial
        - schema:
            type: string
          in: query
          name: codigo
  /api/pos/reporte/caja:
    get:
      description: Reporte de Caja
      summary: Obtener reporte de caja
      tags:
        - Reportes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    venta:
                      type: number
                    premio:
                      type: number
                    tickets:
                      type: integer
                    subtotal:
                      type: number
                    comision:
                      type: number
                    participacion:
                      type: number
                    total:
                      type: number
                    operadora:
                      type: string
                      description: |
                        id de la operadora
                      example: 5fac0cb3f4131413ec042696
                    fecha:
                      type: string
                      example: '2020-11-11 11:00:00'
                    sesionId:
                      type: string
                      example: 5fac0cb3f4131413ec042696
              examples:
                Ejemplo:
                  value:
                    - _id: 5fac0cb3f4131413ec042696
                      venta: 0
                      premio: 0
                      tickets: 0
                      subtotal: 0
                      comision: 0
                      participacion: 0
                      total: 0
                      operadora: 5fac0cb3f4131413ec042696
                      fecha: '2020-11-11 11:00:00'
                      sesionId: 5fac0cb3f4131413ec042696
      operationId: get-api-pos-reporte-caja
      parameters:
        - schema:
            type: string
          in: query
          name: fecha
          required: true
        - schema:
            type: string
            default: ves
            example: ves
            enum:
              - ves
              - usd
              - eur
          in: query
          name: moneda
  /api/pos/reporte/caja/generar:
    get:
      description: Reporte de Caja
      summary: Generar reporte de caja
      tags:
        - Reportes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  mensaje:
                    type: string
      operationId: get-api-pos-reporte-caja-generar
      parameters: []
  /ticket/devolucion:
    post:
      description: Devolucion de ticket
      summary: Devolución de ticket
      operationId: post-ticket-devolucion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  ok:
                    type: boolean
                  mensaje:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                serial:
                  type: string
                sorteo:
                  type: string
                numero:
                  type: string
                razon:
                  type: string
      tags:
        - ticket
  /auth/cambiarclave:
    post:
      summary: ''
      operationId: post-auth-cambiarclave
      responses:
        '200':
          description: OK
      description: Cambiar contraseña de la taquilla
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clave_actual:
                  type: string
                clave_nueva:
                  type: string
              required:
                - clave_actual
      parameters:
        - schema:
            type: string
            example: Bearer af4gs0ds7aas8bba....
          in: header
          name: Authentication
          required: true
          description: JWToken
  /auth/recuperar_clave:
    get:
      summary: Recuperar contraseña
      tags: []
      responses: {}
      operationId: get-auth-recuperar_clave
      description: 'Enviar solicitud para recuperar contraseña, mediante el correo'
components:
  schemas:
    Sorteo:
      title: Sorteo
      type: object
      properties:
        _id:
          type: string
        descripcion:
          type: string
        cierra:
          type: string
          format: date-time
          example: '2020-11-11T00:00:00Z'
        operadora:
          type: string
    Error:
      title: Error
      type: object
      properties:
        error:
          type: string
      description: Modelo para respuestas de error
  securitySchemes: {}
tags:
  - name: sorteos
  - name: ticket
  - name: Sesion
  - name: Reportes
